language: node_js
node_js:
- stable
services:
- mongodb
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g codecov
before_script:
- mongo atkytp --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
- npm test
- codecov
deploy:
  provider: heroku
  api_key:
    secure: XOqGs4f0bBuDZFV42AcMYN3fEpropUaQyEhgs897QF/5IfSGzCs8mhC5Gc5RIMjcOpsGaurq68d1XOupcGcsq0gx3ocnfkI9T+vlYOJJ+Nc2IdwM14bK8HAoFOP7f9Cl1lordVPYgOH+sLJpsiQdM7j1NaPykrzwk+w+GWNbFmv4S5yO6YC1apg531OHFRQ/Nle1+QGZVtrw73ocf1zRwuQSd1yozFdQ5g7usbqSL4SByAtGHMwJWTn/vTDiECLACUEP2HlzuwRd1b2gIE7TgI/aMoOXDZYqsCM96UbPcRsaCgDjICE5RRDdd4A8XwodzBIajHByQxgY38tq2QWYnQuQt7MIhUBUzAPl4KY3kicdVxHid+HxMrTrbAa82yzhmVGkHe49QY4/1JEDRVP6MNNjUjqMe7zEt6Pw9WtSh5yiathhQL7emB2R/vONG80Rh/02mvGAabbnTQ8GIfnG9KPgrkIcUhVT8fEwtkzbEJXlXSY30nI9G9GgSZf4A0zds9enP125SbkjmfnAfJuTXRa+zyoyFWySCkSm9VuBq16YGl3YXkpSn42BKVO1b25LKQSANzD1Ouonm/oTgr1CKtbIF42hWxDleNfi7oW3jM93HbMf36mD5dOYcxSv/4XfyDeNwwi56RdhzFulCaNpvQiyImMxlP5XrGJYF33COBM=
