language: node_js
node_js:
- stable
services:
- mongodb
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g codecov
before_script:
- mongo atkytp --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
- npm test
- codecov
deploy:
  provider: heroku
  api_key:
    secure: sJrECTPGRlcJsjxRLdnJkTcM/534jqkaR/++X1XIQ6bPOB/0gkZASUtIYszwm/zthDYUE8ePOJnp2BhdYBXBk1cDkGtyYlECaOvqxEu6Dq1TyLBwFVCJUrHOMHOivQbLJbhtiw3vCNF8Y05NRzsT1W2V9UK4xco4UqT5k2lC+dIihMg6vEciDhwRd31dCQQsak5FqqFF+1BbqRFTYmJXnzIP9qQHH4SvlSFvYN0WBexfTYGSmNS2oKTK6DUDecnEO4aZkCwKjC6of2xXyCjeR+Kh8pPwPO5BzO2PIkbEpI3Y2jyQL9qRnVa+69TVgxagGDyTApSuVbN6tB1nZJE/FzdQ7MtPLex26nEnEdr5v7Pk3Ro7U0FjNez67c9HcHlrPuWdgWTj63yoPJ6j7KjGSM2jsSRKup161bGfS0p8G5I1gGFLBUefRGADAB1zWO6tBwHxzkRrHMMJJcCrEP7fs6veqhZ9a1kthcs3OYAFbAp7dNiOW3iksVhmb7Vn8cLhprPirMJ8tlUeM7TJlDsRk8kNOe8r/XbroU1RItXXy7APcCR1NM2PxjIKP/WfLkZj+tMBemYgjg7nd0TQr8/tr2H/IkjyzHQUdlcPJ0E5gS7hXTCxPOWzIkhDYquOvlOudSgCHRVF2oErJuZkqh1PEgBpQZc05rkyW85BYUY9yXg=
  app: atkytp-api
  on:
    repo: TKOaly/atkytp2019-game-web
