language: node_js
node_js: 
  - "stable"
services:
  - mongodb
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm install -g codecov
before_script:
  - mongo atkytp --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test
  - codecov